#sudo: required

env:
  DOCKER_COMPOSE_VERSION: 1.14.0

services:
  - docker

before_install:
  - sudo apt update
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - docker-compose --version

before_script:
  - make docker-start
  - sleep 3m
  - docker inspect -f {{.Config.Volumes}} $(docker-compose ps -q php)
  - ls -lah
  - ls -lah web/app
  - ls -lah web/app/vendor/apigen/apigen
  - docker-compose logs --tail="all"

script:
  - make travis
  - make apidoc